export type CareerRole = {
  slug: string;
  title: string;
  category: string;
  summary: string;
  salaryRange: string;
  estimatedMonths: number;
  skills: string[];
  milestones: Array<{
    title: string;
    description: string;
    skills: string[];
  }>;
};

export const careerRoles: CareerRole[] = [
  {
    slug: "cloud-devops-engineer",
    title: "Cloud DevOps Engineer",
    category: "Cloud & infrastructure",
    summary: "Build reliable delivery pipelines and operate cloud services at scale.",
    salaryRange: "$95k–$145k",
    estimatedMonths: 5,
    skills: ["Linux", "Networking", "Git", "Cloud fundamentals", "Containers", "Infrastructure as code", "CI/CD", "Observability"],
    milestones: [
      { title: "Cloud foundations", description: "Understand identity, networking, compute, storage, and cost controls.", skills: ["Cloud fundamentals", "Networking"] },
      { title: "Automation layer", description: "Provision repeatable environments and document the operational contract.", skills: ["Infrastructure as code", "Git"] },
      { title: "Delivery systems", description: "Ship a tested service through a secure, observable deployment pipeline.", skills: ["CI/CD", "Containers", "Observability"] },
    ],
  },
  {
    slug: "site-reliability-engineer",
    title: "Site Reliability Engineer",
    category: "Reliability engineering",
    summary: "Improve availability, performance, and developer velocity through engineering.",
    salaryRange: "$110k–$165k",
    estimatedMonths: 6,
    skills: ["Linux", "Programming", "Distributed systems", "Incident response", "Observability", "Automation", "Cloud architecture"],
    milestones: [
      { title: "Reliability fundamentals", description: "Learn service level objectives, error budgets, and incident practice.", skills: ["Incident response", "Observability"] },
      { title: "Systems engineering", description: "Model failure modes and automate repetitive operational work.", skills: ["Distributed systems", "Automation"] },
      { title: "Production ownership", description: "Design and operate a resilient service with measurable reliability.", skills: ["Cloud architecture", "Programming"] },
    ],
  },
  {
    slug: "security-analyst",
    title: "Cybersecurity Analyst",
    category: "Security",
    summary: "Detect, investigate, and reduce threats across applications and infrastructure.",
    salaryRange: "$75k–$125k",
    estimatedMonths: 5,
    skills: ["Networking", "Operating systems", "Identity", "Threat modeling", "Log analysis", "Incident response", "Security controls"],
    milestones: [
      { title: "Security baseline", description: "Build fluency in identity, protocols, common attack paths, and controls.", skills: ["Networking", "Identity", "Operating systems"] },
      { title: "Detection practice", description: "Turn signals into useful detections and investigate suspicious activity.", skills: ["Log analysis", "Threat modeling"] },
      { title: "Response readiness", description: "Coordinate containment, recovery, and clear post-incident improvements.", skills: ["Incident response", "Security controls"] },
    ],
  },
  {
    slug: "qa-automation-engineer",
    title: "QA Automation Engineer",
    category: "Software quality",
    summary: "Design automated tests that make software releases safer and faster.",
    salaryRange: "$78k–$120k",
    estimatedMonths: 4,
    skills: ["Testing fundamentals", "JavaScript or Python", "API testing", "Browser automation", "CI/CD", "Test design"],
    milestones: [
      { title: "Test strategy", description: "Translate product risks into focused, maintainable test coverage.", skills: ["Testing fundamentals", "Test design"] },
      { title: "Automation systems", description: "Build stable browser and API checks with useful diagnostics.", skills: ["Browser automation", "API testing", "JavaScript or Python"] },
      { title: "Release confidence", description: "Run quality gates in CI and communicate risk clearly.", skills: ["CI/CD"] },
    ],
  },
  {
    slug: "data-analyst",
    title: "Data Analyst",
    category: "Data & decision support",
    summary: "Turn operational data into decisions, forecasts, and measurable outcomes.",
    salaryRange: "$65k–$105k",
    estimatedMonths: 4,
    skills: ["SQL", "Spreadsheets", "Statistics", "Data visualization", "Business communication", "Python basics"],
    milestones: [
      { title: "Data fluency", description: "Query, clean, and validate data from common business systems.", skills: ["SQL", "Spreadsheets"] },
      { title: "Decision models", description: "Use statistics and clear visual narratives to explain what changed.", skills: ["Statistics", "Data visualization"] },
      { title: "Analytical delivery", description: "Automate recurring analysis and recommend measurable actions.", skills: ["Python basics", "Business communication"] },
    ],
  },
  {
    slug: "technical-project-manager",
    title: "Technical Project Manager",
    category: "Product delivery",
    summary: "Coordinate complex technical work from planning through measurable delivery.",
    salaryRange: "$85k–$135k",
    estimatedMonths: 4,
    skills: ["Planning", "Risk management", "Stakeholder communication", "Agile delivery", "Technical literacy", "Metrics"],
    milestones: [
      { title: "Delivery mechanics", description: "Plan milestones, dependencies, ownership, and decision points.", skills: ["Planning", "Agile delivery"] },
      { title: "Risk leadership", description: "Make uncertainty visible and move blockers toward decisions.", skills: ["Risk management", "Stakeholder communication"] },
      { title: "Technical confidence", description: "Connect architecture, trade-offs, and outcomes without losing the team.", skills: ["Technical literacy", "Metrics"] },
    ],
  },
  {
    slug: "frontend-engineer",
    title: "Frontend Engineer",
    category: "Software development",
    summary: "Build accessible, responsive web interfaces and product experiences.",
    salaryRange: "$85k–$145k",
    estimatedMonths: 7,
    skills: ["HTML and CSS", "JavaScript", "TypeScript", "React", "Testing", "Accessibility", "Git"],
    milestones: [
      { title: "Web foundations", description: "Build semantic, responsive pages and understand browser fundamentals.", skills: ["HTML and CSS", "JavaScript"] },
      { title: "Application development", description: "Create typed, component-based interfaces that manage real user flows.", skills: ["TypeScript", "React"] },
      { title: "Production quality", description: "Ship accessible, tested interfaces with a portfolio that demonstrates product thinking.", skills: ["Testing", "Accessibility", "Git"] },
    ],
  },
  {
    slug: "backend-engineer",
    title: "Backend Engineer",
    category: "Software development",
    summary: "Design APIs, services, and data systems that power reliable products.",
    salaryRange: "$95k–$160k",
    estimatedMonths: 8,
    skills: ["Programming", "APIs", "Databases", "Testing", "Security", "Cloud deployment"],
    milestones: [
      { title: "Programming foundations", description: "Write maintainable programs and model data clearly.", skills: ["Programming", "Testing"] },
      { title: "Service design", description: "Build documented APIs backed by a reliable database.", skills: ["APIs", "Databases"] },
      { title: "Production services", description: "Deploy a secure service with monitoring and operational documentation.", skills: ["Security", "Cloud deployment"] },
    ],
  },
  {
    slug: "data-engineer",
    title: "Data Engineer",
    category: "Data platforms",
    summary: "Build dependable pipelines that make data available for decisions and products.",
    salaryRange: "$95k–$155k",
    estimatedMonths: 8,
    skills: ["SQL", "Python", "Data modeling", "ETL", "Cloud storage", "Orchestration", "Data quality"],
    milestones: [
      { title: "Data foundations", description: "Query, model, and validate relational data.", skills: ["SQL", "Data modeling"] },
      { title: "Pipeline building", description: "Move and transform data with repeatable, testable jobs.", skills: ["Python", "ETL", "Data quality"] },
      { title: "Platform operations", description: "Schedule, observe, and secure production data workflows.", skills: ["Cloud storage", "Orchestration"] },
    ],
  },
  {
    slug: "machine-learning-engineer",
    title: "Machine Learning Engineer",
    category: "AI & machine learning",
    summary: "Turn data and models into measurable, reliable product capabilities.",
    salaryRange: "$110k–$180k",
    estimatedMonths: 10,
    skills: ["Python", "Statistics", "Machine learning", "Data pipelines", "Model evaluation", "Deployment"],
    milestones: [
      { title: "Modeling foundations", description: "Understand probability, evaluation, and common supervised learning methods.", skills: ["Statistics", "Machine learning"] },
      { title: "Applied modeling", description: "Create a reproducible training workflow with honest validation.", skills: ["Python", "Model evaluation"] },
      { title: "Model delivery", description: "Serve, monitor, and improve a model in a real application.", skills: ["Data pipelines", "Deployment"] },
    ],
  },
  {
    slug: "ux-ui-designer",
    title: "UX/UI Designer",
    category: "Design",
    summary: "Research user needs and turn them into clear, usable digital experiences.",
    salaryRange: "$65k–$125k",
    estimatedMonths: 6,
    skills: ["User research", "Information architecture", "Wireframing", "Visual design", "Prototyping", "Usability testing"],
    milestones: [
      { title: "Problem discovery", description: "Interview users, frame problems, and map journeys without jumping to solutions.", skills: ["User research", "Information architecture"] },
      { title: "Interface design", description: "Create accessible wireframes and visual systems for key flows.", skills: ["Wireframing", "Visual design"] },
      { title: "Validation", description: "Prototype, test, iterate, and present decisions in a focused case study.", skills: ["Prototyping", "Usability testing"] },
    ],
  },
  {
    slug: "product-manager",
    title: "Product Manager",
    category: "Product",
    summary: "Translate customer problems into prioritized product outcomes and coordinated delivery.",
    salaryRange: "$90k–$160k",
    estimatedMonths: 6,
    skills: ["Discovery", "Prioritization", "Roadmapping", "Writing", "Analytics", "Stakeholder leadership"],
    milestones: [
      { title: "Customer discovery", description: "Gather evidence and define a problem worth solving.", skills: ["Discovery", "Writing"] },
      { title: "Product decisions", description: "Prioritize opportunities and write a clear delivery plan.", skills: ["Prioritization", "Roadmapping"] },
      { title: "Outcome leadership", description: "Coordinate teams and measure whether the product created value.", skills: ["Analytics", "Stakeholder leadership"] },
    ],
  },
  {
    slug: "technical-writer",
    title: "Technical Writer",
    category: "Content & documentation",
    summary: "Make complex products understandable through precise documentation and learning content.",
    salaryRange: "$65k–$115k",
    estimatedMonths: 4,
    skills: ["Technical research", "Information design", "API documentation", "Editing", "Content systems", "Audience empathy"],
    milestones: [
      { title: "Clarity foundations", description: "Explain technical concepts with structure, examples, and the right level of detail.", skills: ["Technical research", "Editing"] },
      { title: "Documentation systems", description: "Create task-based guides and reference documentation for a real product.", skills: ["Information design", "API documentation"] },
      { title: "Content operations", description: "Maintain documentation quality and measure whether readers succeed.", skills: ["Content systems", "Audience empathy"] },
    ],
  },
  {
    slug: "solutions-architect",
    title: "Solutions Architect",
    category: "Technology consulting",
    summary: "Design practical technology solutions that connect business goals, systems, and delivery.",
    salaryRange: "$105k–$175k",
    estimatedMonths: 8,
    skills: ["System design", "Cloud architecture", "Integration", "Security", "Communication", "Trade-offs"],
    milestones: [
      { title: "Architecture fluency", description: "Map requirements to components, interfaces, data flows, and constraints.", skills: ["System design", "Trade-offs"] },
      { title: "Solution design", description: "Produce a secure, scalable design with explicit cost and delivery choices.", skills: ["Cloud architecture", "Integration", "Security"] },
      { title: "Technical influence", description: "Present recommendations and guide implementation across technical and business audiences.", skills: ["Communication"] },
    ],
  },
  {
    slug: "network-administrator",
    title: "Network Administrator",
    category: "IT infrastructure",
    summary: "Operate secure, available networks and troubleshoot connectivity for organizations.",
    salaryRange: "$65k–$110k",
    estimatedMonths: 6,
    skills: ["TCP/IP", "Routing", "Switching", "Firewalls", "Monitoring", "Troubleshooting"],
    milestones: [
      { title: "Network foundations", description: "Understand addressing, protocols, routing, and switching.", skills: ["TCP/IP", "Routing", "Switching"] },
      { title: "Operations practice", description: "Configure, monitor, and document a small network safely.", skills: ["Firewalls", "Monitoring"] },
      { title: "Incident response", description: "Diagnose outages methodically and communicate restoration clearly.", skills: ["Troubleshooting"] },
    ],
  },
  {
    slug: "database-administrator",
    title: "Database Administrator",
    category: "Data infrastructure",
    summary: "Keep databases secure, performant, recoverable, and useful to application teams.",
    salaryRange: "$80k–$135k",
    estimatedMonths: 7,
    skills: ["SQL", "Data modeling", "Backup and recovery", "Performance tuning", "Security", "Automation"],
    milestones: [
      { title: "Database foundations", description: "Model relational data and write reliable SQL.", skills: ["SQL", "Data modeling"] },
      { title: "Safe operations", description: "Plan backups, recovery tests, access controls, and change procedures.", skills: ["Backup and recovery", "Security"] },
      { title: "Performance ownership", description: "Diagnose slow workloads and automate repeatable administration.", skills: ["Performance tuning", "Automation"] },
    ],
  },
  {
    slug: "it-support-specialist",
    title: "IT Support Specialist",
    category: "IT operations",
    summary: "Help people stay productive by resolving technical issues and improving support systems.",
    salaryRange: "$45k–$80k",
    estimatedMonths: 3,
    skills: ["Troubleshooting", "Operating systems", "Networking basics", "Identity and access", "Documentation", "Customer service"],
    milestones: [
      { title: "Support foundations", description: "Troubleshoot common hardware, software, and connectivity issues.", skills: ["Troubleshooting", "Operating systems"] },
      { title: "Environment administration", description: "Manage accounts, devices, permissions, and repeatable setup tasks.", skills: ["Networking basics", "Identity and access"] },
      { title: "Support excellence", description: "Write useful runbooks and improve customer outcomes with clear communication.", skills: ["Documentation", "Customer service"] },
    ],
  },
  {
    slug: "sales-engineer",
    title: "Sales Engineer",
    category: "Technical commercial",
    summary: "Help customers understand, evaluate, and successfully adopt technical products.",
    salaryRange: "$85k–$155k",
    estimatedMonths: 5,
    skills: ["Discovery", "Product demonstrations", "Solution design", "Presentations", "Objection handling", "Business value"],
    milestones: [
      { title: "Customer discovery", description: "Ask strong questions and connect technical requirements to business pain.", skills: ["Discovery", "Business value"] },
      { title: "Technical storytelling", description: "Build credible demonstrations and explain trade-offs to mixed audiences.", skills: ["Product demonstrations", "Presentations"] },
      { title: "Deal support", description: "Design solutions and handle objections without overpromising.", skills: ["Solution design", "Objection handling"] },
    ],
  },
  {
    slug: "customer-success-manager",
    title: "Customer Success Manager",
    category: "Customer operations",
    summary: "Help customers achieve measurable outcomes and build durable product relationships.",
    salaryRange: "$60k–$115k",
    estimatedMonths: 4,
    skills: ["Onboarding", "Relationship management", "Product adoption", "Health metrics", "Communication", "Renewal planning"],
    milestones: [
      { title: "Customer foundations", description: "Run structured onboarding and define success outcomes with customers.", skills: ["Onboarding", "Communication"] },
      { title: "Adoption practice", description: "Use product signals to identify risks and guide customers to value.", skills: ["Product adoption", "Health metrics"] },
      { title: "Account leadership", description: "Build outcome reviews and renewal plans grounded in evidence.", skills: ["Relationship management", "Renewal planning"] },
    ],
  },
  {
    slug: "digital-marketing-specialist",
    title: "Digital Marketing Specialist",
    category: "Marketing",
    summary: "Attract and convert audiences through measurable content, search, email, and campaigns.",
    salaryRange: "$55k–$100k",
    estimatedMonths: 4,
    skills: ["Audience research", "Content strategy", "SEO", "Email marketing", "Analytics", "Experimentation"],
    milestones: [
      { title: "Audience and message", description: "Define a target audience, proposition, and measurable funnel.", skills: ["Audience research", "Content strategy"] },
      { title: "Channel execution", description: "Create search, email, and content campaigns with consistent measurement.", skills: ["SEO", "Email marketing"] },
      { title: "Growth analysis", description: "Interpret campaign data and run focused experiments.", skills: ["Analytics", "Experimentation"] },
    ],
  },
  {
    slug: "financial-analyst",
    title: "Financial Analyst",
    category: "Finance",
    summary: "Turn financial and operational data into forecasts, decisions, and clear recommendations.",
    salaryRange: "$65k–$115k",
    estimatedMonths: 5,
    skills: ["Financial statements", "Excel", "Forecasting", "SQL basics", "Business writing", "Presentation"],
    milestones: [
      { title: "Finance foundations", description: "Read financial statements and understand the drivers behind performance.", skills: ["Financial statements", "Excel"] },
      { title: "Forecasting practice", description: "Build transparent models with assumptions, scenarios, and sensitivity checks.", skills: ["Forecasting", "SQL basics"] },
      { title: "Decision support", description: "Present concise recommendations with evidence and business context.", skills: ["Business writing", "Presentation"] },
    ],
  },
  {
    slug: "operations-analyst",
    title: "Operations Analyst",
    category: "Business operations",
    summary: "Improve processes and performance by combining data, systems thinking, and practical change.",
    salaryRange: "$60k–$105k",
    estimatedMonths: 4,
    skills: ["Process mapping", "Excel", "Data analysis", "Root cause analysis", "Project coordination", "Communication"],
    milestones: [
      { title: "Process discovery", description: "Map how work happens and identify measurable friction.", skills: ["Process mapping", "Root cause analysis"] },
      { title: "Analysis practice", description: "Use spreadsheets and data to quantify opportunities and test hypotheses.", skills: ["Excel", "Data analysis"] },
      { title: "Improvement delivery", description: "Coordinate a change, track results, and communicate what improved.", skills: ["Project coordination", "Communication"] },
    ],
  },
  {
    slug: "hr-people-operations-specialist",
    title: "People Operations Specialist",
    category: "People operations",
    summary: "Create consistent, human-centered systems for hiring, onboarding, and employee support.",
    salaryRange: "$55k–$100k",
    estimatedMonths: 4,
    skills: ["HR operations", "Employee experience", "Policy literacy", "People analytics", "Communication", "Confidentiality"],
    milestones: [
      { title: "People operations foundations", description: "Understand lifecycle processes, documentation, and employee service standards.", skills: ["HR operations", "Policy literacy"] },
      { title: "Experience design", description: "Improve onboarding and support journeys with empathy and clear ownership.", skills: ["Employee experience", "Communication"] },
      { title: "Responsible operations", description: "Use people data carefully and handle sensitive information professionally.", skills: ["People analytics", "Confidentiality"] },
    ],
  },
  {
    slug: "supply-chain-coordinator",
    title: "Supply Chain Coordinator",
    category: "Supply chain",
    summary: "Coordinate inventory, suppliers, logistics, and operational decisions across a value chain.",
    salaryRange: "$50k–$95k",
    estimatedMonths: 4,
    skills: ["Inventory planning", "Procurement", "Excel", "Logistics", "Forecasting", "Supplier communication"],
    milestones: [
      { title: "Supply chain foundations", description: "Understand demand, inventory, purchasing, fulfillment, and lead times.", skills: ["Inventory planning", "Logistics"] },
      { title: "Planning practice", description: "Build a simple forecast and identify service and cost trade-offs.", skills: ["Excel", "Forecasting"] },
      { title: "Coordination", description: "Communicate constraints and actions across suppliers and internal teams.", skills: ["Procurement", "Supplier communication"] },
    ],
  },
  {
    slug: "healthcare-administrator",
    title: "Healthcare Administrator",
    category: "Healthcare operations",
    summary: "Coordinate services, people, and processes that help healthcare organizations run well.",
    salaryRange: "$55k–$105k",
    estimatedMonths: 5,
    skills: ["Healthcare operations", "Scheduling", "Compliance awareness", "Data literacy", "Budgeting", "Patient communication"],
    milestones: [
      { title: "Healthcare context", description: "Learn how care operations, privacy, scheduling, and quality interact.", skills: ["Healthcare operations", "Compliance awareness"] },
      { title: "Operational control", description: "Coordinate schedules, resources, and basic performance reporting.", skills: ["Scheduling", "Data literacy"] },
      { title: "Service improvement", description: "Improve an operational workflow while keeping patient experience central.", skills: ["Budgeting", "Patient communication"] },
    ],
  },
  {
    slug: "renewable-energy-technician",
    title: "Renewable Energy Technician",
    category: "Skilled technical work",
    summary: "Install, inspect, and maintain renewable energy equipment safely and reliably.",
    salaryRange: "$50k–$95k",
    estimatedMonths: 8,
    skills: ["Electrical safety", "Systems inspection", "Technical documentation", "Tools and measurement", "Worksite safety", "Customer communication"],
    milestones: [
      { title: "Safety and fundamentals", description: "Build electrical awareness, safe work habits, and equipment literacy.", skills: ["Electrical safety", "Worksite safety"] },
      { title: "Field practice", description: "Use tools and measurements to install or inspect systems under supervision.", skills: ["Systems inspection", "Tools and measurement"] },
      { title: "Professional delivery", description: "Document work accurately and explain maintenance clearly to customers.", skills: ["Technical documentation", "Customer communication"] },
    ],
  },
  {
    slug: "project-coordinator",
    title: "Project Coordinator",
    category: "Project delivery",
    summary: "Keep projects organized through clear plans, follow-up, documentation, and communication.",
    salaryRange: "$50k–$90k",
    estimatedMonths: 3,
    skills: ["Scheduling", "Task tracking", "Meeting facilitation", "Documentation", "Risk awareness", "Communication"],
    milestones: [
      { title: "Project mechanics", description: "Track work, owners, dates, dependencies, and decisions.", skills: ["Scheduling", "Task tracking"] },
      { title: "Team coordination", description: "Run effective meetings and turn discussion into accountable next steps.", skills: ["Meeting facilitation", "Communication"] },
      { title: "Delivery visibility", description: "Maintain project records and surface risks early.", skills: ["Documentation", "Risk awareness"] },
    ],
  },
];

export function getCareerRole(slug: string) {
  return careerRoles.find((role) => role.slug === slug);
}
